### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario (3) (#10)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#10]
Al hacer click en el botón "Volver".
![image](https://cloud.githubusercontent.com/assets/11543134/24868651/121ac62e-1de7-11e7-898f-58734ecd739a.png)
Devuelve msj de error.
![image](https://cloud.githubusercontent.com/assets/11543134/24868657/179012ee-1de7-11e7-8f72-67afdaf615d9.png)

**Comment by alewalsh** [comment]
Ya se solucionó la redirección del botón volver en Agregar Usuario.

**Comment by alewalsh** [comment]
Se probó y redirecciona correctamente al Inicio.
