### ISSUE TITLE
Siniestros/ Versión 1.0/ Informacion del Usuario(1) (#11)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#11]
Al querer cambiar la contraseña del usuario, al darle guardar devuelve msj de error.

![image](https://cloud.githubusercontent.com/assets/11543134/24868743/5b129938-1de7-11e7-9167-95b2a04f1019.png)

**Comment by alewalsh** [comment]
Se reviso el código y se solucionaron inconsistencias que podrían traer errores. Sin embargo, por los múltiples errores con respecto al servicio, queda pendiente de revisión en testing al publicarlo.

**Comment by alewalsh** [comment]
Se comprobó que cambia la contraseña correctamente.
