### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuarios (4) (Testing #19)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#12]
- Deja crear usuarios ya existentes, debería validar si el "Nombre de Usuario" ya existe.
- Permite crear un usuario que ya existe pero con distinto perfil. Ej: el usuario "36273257" tiene perfil Administrador y de Consulta.

![image](https://cloud.githubusercontent.com/assets/11543134/25196457/249a8ad2-2517-11e7-9ad3-d725bdc831cb.png)

**Comment by rominariquelme** [comment]
Se agrega la validacion del nombre de Usuario

**Comment by alewalsh** [comment]
Se comprobó que funciona correctamente la validación, no deja crear dos usuarios con el mismo nombre de usuario. Por lo tanto, ya no podrá haber dos nombres de usuario con distintos perfiles.
