### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Usuarios (1) (Testing #20)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#13]
Si se desactiva un usuario.
![image](https://cloud.githubusercontent.com/assets/11543134/25196510/4d17dee2-2517-11e7-8b12-8b9f1e9dec1d.png)

desactivar
Permite seguir logueandote con el usuario que se encuentra "desactivado".

Si me encuentro en la Pág. 2 de la grilla y quiero desactivar un usuario al hacer click en el botón "Desactivar" me lleva a la Pág. 1, me tendría que mantener en la Página que me encuentro.

**Comment by alewalsh** [comment]
Solucionado, ya no deja loguearse con usuarios desactivados y se corrigió el comportamiento de la grilla de consultar usuarios.

**Comment by alewalsh** [comment]
Ya no permite loguearse con usuarios desactivados.
También, sostiene la pagina al desactivar o activar un usuario.
