### ISSUE TITLE
Siniestros/ Versión 1.0/Consultar Perfil(2) (Testing#6)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#14]
- Si un Perfil se encuentra desactivado
![image](https://cloud.githubusercontent.com/assets/11543134/25196583/7ea33c86-2517-11e7-8450-4d38dfedd8f7.png)
- Cuando Vamos a dar de alta un usuario los perfiles que se encuentran desactivados no se deberían poder seleccionar.
![image](https://cloud.githubusercontent.com/assets/11543134/25196600/8a4973ca-2517-11e7-9108-e5d2aea024ee.png)

**Comment by alewalsh** [comment]
Solucionado, ya no aparecen los perfiles desactivados en el combo de agregar usuario.

Bonus track: Se corrigio un comportamiento erroneo en la grilla de consultar perfiles.

**Comment by alewalsh** [comment]
Se comprobó que no aparezcan perfiles desactivados al querer crear un usuario.
