### ISSUE TITLE
Siniestros/Versión 1.0/Agregar Perfil (1) (Testing #3)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#15]
Permite dar de alta Perfiles que ya existen, mismo nombre y mismos permisos.
![image](https://cloud.githubusercontent.com/assets/11543134/25196651/a4fefe42-2517-11e7-80cc-b77f0f6b90c0.png)

**Comment by rominariquelme** [comment]
Se agrega la validacion del nombre de Perfil

**Comment by alewalsh** [comment]
La validación del nombre de Perfil esta funcionando correctamente.
