### ISSUE TITLE
Siniestros/ Versión 1.0/ Registro Siniestro, Datos Denunciante(1) (Testing #21)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#16]
- Fecha de Carga no podrá ser mayor a la fecha actual, si se carga a mano la fecha permite cargar mayor a la del día de hoy

- El control “Mail” es el único que permitirá caracteres especiales (Ej: “@”, “.”), permite cargar caracteres especiales en cualquier campo.

![image](https://cloud.githubusercontent.com/assets/11543134/25234208/c5414d2c-25b7-11e7-86cb-bea775e2fe4a.png)

**Comment by alewalsh** [comment]
- Fecha de Carga no podrá ser mayor a la fecha actual, si se carga a mano la fecha permite cargar mayor a la del día de hoy.

Se corrigieron detalles, pero probando con la fecha de la captura, la validación funciona correctamente al intentar guardar.

- El control “Mail” es el único que permitirá caracteres especiales (Ej: “@”, “.”), permite cargar caracteres especiales en cualquier campo.

Ya se agregaron expresiones regulares para validar todos los campos, nuevamente se aclara que los campos se validan al intentar guardar el siniestro.

**Comment by alewalsh** [comment]
Se comprobó que no se puede ingresar una fecha mayor al día de la fecha.
Solo el mail permite caracteres especiales, esto se valida al querer guardar el siniestro.
