### ISSUE TITLE
Siniestro/ Versión 1.0/ Registrar Siniestro, Datos Accidentado(2) (Testing #22)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#17]
- El control “Mail” es el único que permitirá caracteres especiales (Ej: “@”, “.”), permite caracteres especiales en cualquier campo.

![image](https://cloud.githubusercontent.com/assets/11543134/25235361/49f99436-25bb-11e7-9b14-89927975f21d.png)

- Cuando se selecciona "Provincia" & Partido devuelve msj de error.

![image](https://cloud.githubusercontent.com/assets/11543134/25235374/55c32be2-25bb-11e7-91c6-525cd8be90c9.png)

**Comment by alewalsh** [comment]
Ya no se permiten caracteres especiales en los campos que no corresponden y se corrigio la consulta de localidades.
