### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro, Evaluación Jurídica(3) (Testing #23)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#18]
- DropDown “Seguro”: Si se sabe que NO posee, elegir “No", no aparece la opción para seleccionarla.

![image](https://cloud.githubusercontent.com/assets/11543134/25235429/7b2ebd88-25bb-11e7-9a58-68cd52f0fbaa.png)

**Comment by alewalsh** [comment]
Se agregó la opcion correspondiente.

**Comment by alewalsh** [comment]
Se comprobó que aparezca la opción "NO" en el dropdown Seguro.
