### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro, Evaluación Social(5) ( Testing#24)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#19]
- DropDown “Seguro”: Si se sabe que NO posee, elegir “No", no aparece la opción para seleccionarla.
![image](https://cloud.githubusercontent.com/assets/11543134/25243781/9fd78462-25d4-11e7-8d0a-9e6ee048e249.png)

- El Control “Posee trabajo” dice "Independencia" y debería ser "Independiente" .
![image](https://cloud.githubusercontent.com/assets/11543134/25243787/a7aa4896-25d4-11e7-8783-4d701115df09.png)

**Comment by alewalsh** [comment]
No hay combo Seguro en Evaluación Social, por lo que asumo que se refieren al combo Obra Social. Ya se solucionó tambien la opcion Independiente en el combo Posee Trabajo.
