### ISSUE TITLE
Creacion Base de datos

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#2]
Adjunto el diagrama de la base de datos.
[BD_Siniestros.docx](https://github.com/leoimoli/Legales-Proyecto-Registro-de-Siniestros/files/608909/BD_Siniestros.docx)

# La extencion del documento es .vsd

**Comment by alewalsh** [comment]
Se finalizo la creación de la base de datos.
