### ISSUE TITLE
Siniestro/ Versión 1.0/ Registrar Siniestro, Intervención ANSV(6) ( Testing #25)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#20]
- Se deberá cargar en la base las direcciones de la ANSV en caso de que el control “Intervención a otra dirección de ANSV” se seleccione en "SI".
![image](https://cloud.githubusercontent.com/assets/11543134/25243816/c61c6fac-25d4-11e7-95fa-deb900f8e866.png)
![image](https://cloud.githubusercontent.com/assets/11543134/25243819/c8d7604e-25d4-11e7-9532-739d7bc576be.png)

**Comment by alewalsh** [comment]
Se cargaron las direcciones disponibles en el listado del sistema de RRHH.

**Comment by alewalsh** [comment]
Se comprobó que en la base de datos de testing estén las direcciones cargadas.
