### ISSUE TITLE
Siniestro/ Versión 1.0/ Log(2) (Testing #26)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#21]
- Desde la pantalla de login se deberá quitar. ya que no cumplen ninguna función.
![image](https://cloud.githubusercontent.com/assets/11543134/25245643/7ec6e1e4-25db-11e7-93b0-b6c1f7e36bc1.png)

- También de se deberá quitar el cartel.
![image](https://cloud.githubusercontent.com/assets/11543134/25245649/86f69d50-25db-11e7-9e45-c7d32c4ee70b.png)
tendrá que ingresar al sistema directamente.

- Cambiar el color de la fuente y cambiar "Ingrese a su cuenta" por "Auntenticación de Usuarios".
![image](https://cloud.githubusercontent.com/assets/11543134/25245661/938a79ba-25db-11e7-8634-bf4abb3a399c.png)

**Comment by alewalsh** [comment]
Se corrigieron los detalles aclarados y un par de cosas que vi adicionales.
