### ISSUE TITLE
Siniestro/ Versión 1.0/ Consulta Perfil(3). (Testing #27)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#22]
- Acortar los campos "nombre" y "estado" (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![image](https://cloud.githubusercontent.com/assets/11543134/25245717/cd84cdfa-25db-11e7-8ce4-1e6e06bd8749.png)
- Cuando se ingresa al menú de consulta, la grilla no debe aparecer si no se realizó una consulta. (ESTE PUNTO REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![image](https://cloud.githubusercontent.com/assets/11543134/25245724/d3bb11ac-25db-11e7-96c6-3969e75de709.png)
- *Deben ser misma fuente y color (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![image](https://cloud.githubusercontent.com/assets/11543134/25245737/db5fb76e-25db-11e7-99a5-7a41d7af44fb.png)

**Comment by alewalsh** [comment]
Se corrigieron todos los consultar.

**Comment by alewalsh** [comment]
Se acortaron todos los filtros de busqueda en las pantallas consultar. 
Ya no consulta en el primer ingreso.
Los placeholder tienen todos el mismo color de fuente.

**Comment by leoimoli** [comment]
- Cuando se ingresa al menú "Consulta Perfiles", la grilla no aparece correctamente, pero luego si se hace una consulta e ingreso Ej: a la pág. N° 3 y navego por otras pantallas, cuando vuelvo a ingresar a "Consulta Perfiles" sigue mostrando la última consulta que se realizó. (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![image](https://cloud.githubusercontent.com/assets/11543134/25853962/d40fc1e8-34a4-11e7-98f2-3684ace2a088.png)

- Si se selecciona buscar "Por Filtro" debe ser obligatorio consultar por "Nombre" o "Estado" en caso de no completar ninguno de los dos campos debe mostrar un msj de recordatorio y no mostrar ningun resultado. (REPLICAR EN TODAS LAS PANTALLAS DE CONSULTA).
![image](https://cloud.githubusercontent.com/assets/11543134/25853980/df31f640-34a4-11e7-8895-a909a7d048be.png)

- En caso de editar el Nombre y Permisos de un Perfil que ya existe, la operación se realiza con éxito, debe mostrar un msj de que ese perfil ya existe. Hoy te permite realizar la edición.
- Alinear el botón "Consultar" (rEPLICAR EN LA PANTALLA "CONSULTA USUARIOS).
![image](https://cloud.githubusercontent.com/assets/11543134/25853999/ed81d06c-34a4-11e7-9eda-7c8ee3c2fa93.png)

**Comment by rominariquelme** [comment]
Al buscar por filtro debe ingresar algún criterio, de lo contrario no devuelve resultado.
El boton consultar se alineo.
limpia todas las consultas.

**Comment by alewalsh** [comment]
Ya hace bien el proceso de edicion.
