### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuarios (5) (Testing #28)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#23]
- Que se pueda editar un usuario (todos los campos menos el Nombre Usuario) y cambiar/agregar/quitar el Perfil.

**Comment by alewalsh** [comment]
Se creó la pantalla editar usuario, que se puede acceder desde el consultar usuario.
Sobre el comentario de "y cambiar/agregar/quitar el Perfil." se interpretó que un usuario solo debía poder cambiar de perfil, dado que no puede NO tener un perfil por los permisos ni tampoco puede tener más de un perfil. Queda aclarado por si vuelve a ser reportado.
