### ISSUE TITLE
Siniestros/ Versión 1.0/ Perfiles(2) #29

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#24]
Que se pueda ver los menú que tiene cargado cada perfil y que se puedan editar los mismos.

Permite crear perfiles con todas las pantallas desactivadas.

En la grilla cambiar "Nombre" por "Menú".

![](https://cloud.githubusercontent.com/assets/27014552/25277997/516a4564-2677-11e7-8ef3-843a64ad4ce3.jpg)
Agregar tilde a "Menú Principal".

![](https://cloud.githubusercontent.com/assets/27014552/25278037/8109a5b2-2677-11e7-9527-d536941a134f.jpg)

**Comment by alewalsh** [comment]
Los cambios fueron realizados pero no se puede probar ni localmente por la caída del enlace con moreno. Asi que no se reporta como cerrado hasta poder probarlo.

**Comment by alewalsh** [comment]
Se probaron los cambios y están funcionando correctamente. Queda pendiente comprobar si "Que se pueda ver los menú que tiene cargado cada perfil" implica una nueva vista de ver detalle, debido a que en el editar puede verse el detalle de permisos disponibles.

**Comment by alewalsh** [comment]
Se pueden ver los permisos de cada perfil.
Se pueden editar los permisos de cada perfil.
Ya no permite crear perfiles sin permisos.
Se cambió Nombre por Menú.
También se agregó la tilde a Menú en Menú Principal.

**Comment by leoimoli** [comment]
- Cuando se da de alta un perfil (exitosamente), y vamos a dar de alta otro y seleccionamos un menú muestra los menú seleccionados del perfil que se dio de alta anteriormente.
![image](https://cloud.githubusercontent.com/assets/11543134/25854078/2b0c7068-34a5-11e7-9148-36060698b108.png)

**Comment by alewalsh** [comment]
Ya se corrigió el error que provocaba el cambio en los menues.
