### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Usuarios (1) #20

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#25]
Si se desactiva un usuario.

![](https://cloud.githubusercontent.com/assets/27014552/25183382/cbe1c942-24ed-11e7-8612-de426208433b.jpg)

Permite seguir logueandote con el usuario que se encuentra "desactivado".

Si me encuentro en la Pág. 2 de la grilla y quiero desactivar un usuario al hacer click en el botón "Desactivar" me lleva a la Pág. 1, me tendría que mantener en la Página que me encuentro.

**Comment by alewalsh** [comment]
Este ticket ya habia sido resuelto previamente: https://github.com/leoimoli/Legales-Proyecto-Registro-de-Siniestros/issues/13

**Comment by leoimoli** [comment]
- Cuando se quiere Activar o Desactivar un usuario, cuando hacemos click sobre el botón refresca la
pantalla, debería seguir mostrando la grilla.
![image](https://cloud.githubusercontent.com/assets/11543134/25854189/90e62960-34a5-11e7-95bf-f192607a42aa.png)

![image](https://cloud.githubusercontent.com/assets/11543134/25854201/97a53548-34a5-11e7-9139-5735de6e09f7.png)

- Cuando se quiera editar un usuario los campos "Contraseña" deberán aparecer deshabilitados, se deberá agregar un botón "Resetear Contraseña" que mostrará los tres campos "Contraseña" (TODOS DEBEN SER OBLIGATORIOS).
- Contraseña Actual.
- Nueva Contraseña.
- Repetir Contraseña.
Cambiar el botón "Volver" por "Cancelar".
- Alinear botón "Consultar"
![image](https://cloud.githubusercontent.com/assets/11543134/25854240/b3ea4d56-34a5-11e7-81ac-53416d22a33d.png)

- Una vez que se edita y le damos al botón "Cerrar" del msj que se editó exitosamente, deberá volver a la pantalla anterior.
![image](https://cloud.githubusercontent.com/assets/11543134/25854258/bbe1a4d2-34a5-11e7-9727-816235d2aa04.png)

**Comment by rominariquelme** [comment]
Al cerrar el modal vuelve a la paguina anterior.(si es la unica opcion)
Se alineo el boton consulta.
Activa y desactiva Usuario sin que se pierda la vista dela tabla.

**Comment by alewalsh** [comment]
Ya vuelve correctamente a la pantalla de Consulta luego de editar exitosamente.
