### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro #30

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#26]
El botón "guardar" cambiar por "Finalizar"

![](https://cloud.githubusercontent.com/assets/27014552/25278413/397d4bf2-2679-11e7-8d89-c28896519e3e.jpg)
Se deberá quitar los msj que muestra en verde guardando los datos del denunciante.

![](https://cloud.githubusercontent.com/assets/27014552/25278492/83a2dba2-2679-11e7-9950-2632a9acd17e.jpg)

Agregar un botón "CANCELAR" en todas las pestañas que realice un "borrarlógico" de todo lo que esté cargado.

Cuando se finalice la carga de un registro siniestro exitoso debe mostrar un cartel de confirmación,
"El siniestro se ha guardado correctamente con el N° 999". (REPLICAR EL CARTEL DE MSJ EN TODAS LAS PANTALLAS DE ALTA).

![](https://cloud.githubusercontent.com/assets/27014552/25278599/147aefde-267a-11e7-9660-abcb41eda7cf.png)

** * Puntos a parte: intentar que las pantallas no refresquen tanto al hacer click en botones o carga de campos, etc.**

** * Si se puede que sea un azul mas claro.**
azul
![](https://cloud.githubusercontent.com/assets/27014552/25278740/baad5b44-267a-11e7-9c0f-da691547bf20.jpg)

** * Quitar.**
2016

![](https://cloud.githubusercontent.com/assets/27014552/25278917/33a1e63c-267b-11e7-9227-119f7bde2951.jpg)

**Comment by rominariquelme** [comment]
-Se cambio El nombre del boton guardar por finalizar.
-Se sacaron los msj que muestra en verde guardando los datos del denunciante.
-Se agrega la funciones para limpiar los campos de las pantallasde alta al precionar el botón "CANCELAR" .
-Se saco 2016 del footer.
-Se crea un nuevo ticket para crear un modal de confirmacion de alta

**Comment by alewalsh** [comment]
Se probó que se haya cambiado el nombre del boton, se sacaron los mensajes en verde del insertar denunciante y accidentado.
Se agregaron modals para cada pantalla de alta.
El tema de que las pantallas refresquen menos queda pendiente para una versión posterior.
La edicion de la imagen por un azul más claro requiere un poco más de tiempo, asi que tambien queda para una version posterior.
Tambien se verifico que se haya quitado el 2016 del footer.

**Comment by leoimoli** [comment]
- Cuando hacemos click en el botón cancelar en "Evaluación Jurídica", cuando los campos son check para seleccionar o radio button no los muestra como "por defecto".
![image](https://cloud.githubusercontent.com/assets/11543134/25854430/5023cf8a-34a6-11e7-8eb9-01ca580c6d63.png)
- Al hacer click en el botón cancelar me debe borrar todo lo que tenga cargado en todas las pestañas, hoy borra por pestañas.
- Si le damos F5 en una pantalla con campos cargados, debe refrescar la pantalla y borrar los campos que teníamos cargados.

**Comment by rominariquelme** [comment]
Se limpian los check de Evaluacion Jurídica.
El boton cancelar borra todo lo cargado.
Al precionar F5 se borran todos los campos y se dirije a la primer pestaña
