### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Siniestros (1) (Testing #31)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#27]
- Cuando ingresamos a la pantalla "Consultar Siniestro" no debe realizar la consulta.
![image](https://cloud.githubusercontent.com/assets/11543134/25282059/bd9ef1cc-2685-11e7-9242-bf5f29311a4f.png)
- El botón "Limpiar" no está funcionando (separar un poco del botón "Consultar").
![image](https://cloud.githubusercontent.com/assets/11543134/25282071/c533dc04-2685-11e7-9d95-8d843b159c85.png)

- Alinear los campos y achicar los campos fechas.
![image](https://cloud.githubusercontent.com/assets/11543134/25282076/ccf0655c-2685-11e7-8f50-0b415ae56c05.png)

- Quitar la hora de la "fecha de carga".
![image](https://cloud.githubusercontent.com/assets/11543134/25282088/d4e67d5a-2685-11e7-99dd-95e5c114ebab.png)

- Si quiero consultar un siniestro por fecha Ej: cargué un siniestro con la fecha 21/04/2017, para que me lo muestro tengo que consultar en "fecha Desde" por 20/04/2017, si consulto por el 21/04/2017 no me lo trae (me dice que no hay siniestro cargado).}

- Cuando quiero consultar por Provincia, al seleccionar una provincia hace la consulta sin hacer click en el botón "Consultar". Y si selecciono un partido devuelve msj de error.
![image](https://cloud.githubusercontent.com/assets/11543134/25282110/e7198440-2685-11e7-939d-cfbd746ecf75.png)

**Comment by rominariquelme** [comment]
Resuelto

**Comment by leoimoli** [comment]
- El botón "Limpiar" no borra el campo Tipo Documento.
- Así deben quedar los campos fecha.
![image](https://cloud.githubusercontent.com/assets/11543134/25854502/97067812-34a6-11e7-8afa-96c3eb753f4d.png)
- Cuando se quiere realizar consultar por el campo fecha rompe, Ej: si estamos en la pantalla de consultar siniestros y hacemos click sobre "Consultar Siniestros" los campos fechas se muestran con hora, si se quiere seleccionar una provincia no te lo permite(te debe poder dejar seleccionar Provincia/Partido..)
![image](https://cloud.githubusercontent.com/assets/11543134/25854524/aa5f1338-34a6-11e7-8491-7caa87286548.png)

**Comment by alewalsh** [comment]
El limpiar ya funciona correctamente.

**Comment by rominariquelme** [comment]
La fecha se ingresa correctamente y se cambio la alineacion de los campos
