### ISSUE TITLE
Siniestro/ versión 1.0/ Consultar Siniestro, Ver (2) (Testing #32)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#28]
- Al seleccionar "VER" de un siniestro pestaña "Dato Denunciante" quitar la hora en Fecha de carga
![image](https://cloud.githubusercontent.com/assets/11543134/25282169/15bbd186-2686-11e7-99f2-13bc3cfc6e11.png)
 
- Agregar el N° del siniestro que se está mostrando
![image](https://cloud.githubusercontent.com/assets/11543134/25282193/20245256-2686-11e7-9ebd-d89a180df358.png)

- En caso de que el campo vaya vacío porque no es obligatorio, en el detalle que se muestre con un guión ** "-" ** hoy los muestra "No Hay datos" o "NO ESPECÍFICA" .
![image](https://cloud.githubusercontent.com/assets/11543134/25282203/2e262988-2686-11e7-9090-0aa5e31a9789.png)

- El botón solo debe decir Volver.
![image](https://cloud.githubusercontent.com/assets/11543134/25282213/37a0a7c2-2686-11e7-98d3-9704e002d497.png)

- Faltaria agregar el Botón "Imprimir" para darle la posibilidad al Usuario.
![image](https://cloud.githubusercontent.com/assets/11543134/25282233/43e350b6-2686-11e7-8ff4-bd7057e5ce75.png)

**Comment by alewalsh** [comment]
Fueron corregidos estos errores.

**Comment by alewalsh** [comment]
Se verificaron que todos estos cambios esten funcionando.

**Comment by leoimoli** [comment]
- Quitar del msj "Resultado de la operación:" (REPLICAR EN TODOS LAS PANTALLAS).
![image](https://cloud.githubusercontent.com/assets/11543134/25854119/56ee83d8-34a5-11e7-9e98-f96fb9af9bf0.png)
- Separar por ítems en caso de que e msj sea. "Las contraseñas no coinciden.No se han completado todos los campos obligatorios."
![image](https://cloud.githubusercontent.com/assets/11543134/25854131/5faaefde-34a5-11e7-953c-95da212b6348.png)

- Alinear el botón "Guardar".
![image](https://cloud.githubusercontent.com/assets/11543134/25854141/68aa2fbe-34a5-11e7-9d31-04ecfd5ea25f.png)

**Comment by leoimoli** [comment]
- Al querer imprimir el siniestro devuelve lo siguiente.
![image](https://cloud.githubusercontent.com/assets/11543134/25854372/26eabf02-34a6-11e7-81c5-858e47994179.png)

**Comment by alewalsh** [comment]
Se corrigió el resultado del imprimir siniestro.

**Comment by alewalsh** [comment]
Se quitó el mensaje de todos los modal.

**Comment by alewalsh** [comment]
Se alinearon todos los botones con respecto a sus campos.

**Comment by alewalsh** [comment]
En todos los casos se separaron los mensajes de error con un salto de linea, para todas las pantallas.
