### ISSUE TITLE
Siniestros/ Versión 1.0/ Consultar Siniestro (3) #33

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#29]
Una vez que se dio de alta un siniestro, hay 15 minutos para poder editar el siniestro, no está apareciendo la opción.

![](https://cloud.githubusercontent.com/assets/27014552/25281702/8760de96-2684-11e7-8f13-ab27e450aa18.jpg)

Cambiar el nombre de la columna en la grilla "Ver" por "Detalle".

![](https://cloud.githubusercontent.com/assets/27014552/25281857/1b793510-2685-11e7-8ad4-0c5922e9c310.jpg)

**Comment by rominariquelme** [comment]
El primer error no se pudo reproducir y se cambio "ver" por "Detalle"
