### ISSUE TITLE
Siniestros/Versión 1.0/Agregar Perfil (1) (#3)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#3]
Cuando completamos el campo "Nombre" y el campo "Estado" y hacemos click en el botón "Guardar" devuelve msj que no se ha podido crear correctamente.

![image](https://cloud.githubusercontent.com/assets/11543134/24866225/e78ae558-1ddf-11e7-9233-85ad5ad3a27b.png)

**Comment by alewalsh** [comment]
Localmente funciona, por lo que se va a probar posteriormente en la publicación.

**Comment by alewalsh** [comment]
No se puede replicar por el hecho de que hay una nueva funcionalidad que también requiere los permisos para este perfil a agregar. Sin embargo, agregando como mínimo un permiso, realiza correctamente el insert.
