### ISSUE TITLE
Siniestro/ Versión 1.0/ Registro Siniestro #34

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#30]
Pestaña Datos Denunciantes : si seleccionamos Tipo de Documento "Pasaporte", N° Documento "36273257A" y la Provincia "Salta" me borra todo...

![](https://cloud.githubusercontent.com/assets/27014552/25282722/b7074088-2687-11e7-96c2-5f515d45d2b9.jpg)

**Comment by rominariquelme** [comment]
no se pudo reproducie el error
![34](https://cloud.githubusercontent.com/assets/5148193/25434297/1feffc56-2a62-11e7-84d0-d5c97b0723ac.PNG)

**Comment by alewalsh** [comment]
Se comprobó que ya no sucede ese error.

**Comment by leoimoli** [comment]
- Ahora pasa con la provincia Misiones...

**Comment by alewalsh** [comment]
Ese error ya se eliminó, era una variable de sesión que quedaba colgada entre el cambio de pantallas.

**Comment by leoimoli** [comment]
- Sigue ocurriendo una vez que hacemos click en el botón cancelar, y luego seleccionamos una provincia en la pestaña "Dato Denunciante" te autodirige a la pestaña "Evaluación Jurídica".

- Al darle Finalizar te vacía los campos que se habían cargado.

**Comment by alewalsh** [comment]
Ya se solucionaron ambos errores.
