### ISSUE TITLE
Siniestros/ Versión 1.0/ Registrar Siniestro

### ISSUE THREAD

**Issue by rominariquelme** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#31]
Cuando se finalice la carga de un registro siniestro exitoso debe mostrar un cartel de confirmación,
"El siniestro se ha guardado correctamente con el N° 999". (REPLICAR EL CARTEL DE MSJ EN TODAS LAS PANTALLAS DE ALTA).

**Comment by alewalsh** [comment]
Se agregó un modal para todas las pantallas agregar.

**Comment by alewalsh** [comment]
Se verificó que el modal esté presente en todos los agregar.
