### ISSUE TITLE
Siniestros/Versión 1.0/ Agregar Perfil (#4)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#4]
En esta pantalla quedaría agregar que permisos y acceso tendrá el perfil , Ej: si se agrega un Perfil Consulta de Siniestros, se debería poder seleccionar que este perfil debería solo poder acceder a la pantalla "Consultar Siniestros".

**Comment by alewalsh** [comment]
Se hizo una tabla para seleccionar permisos y la restricción de que algo debe haber seleccionado si o si.

**Comment by alewalsh** [comment]
Se probó esta adición a la pantalla Agregar Perfil y funciona correctamente. Tira error si no hay ningún permiso seleccionado y recién deja crear cuando hay por lo menos uno.
