### ISSUE TITLE
Errores Reportados--(Testing #82)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#47]
- En el módulo usuario al seleccionar la opción "Coordinador" se mostrará un combo de SELECCIÓN MÚLTIPLE con todos los operadores (Hoy solo permite seleccionar un operador), esta funcionalidad se debe replicar también en el "EDITAR".
![image](https://user-images.githubusercontent.com/11543134/34257046-f06f7506-e636-11e7-8fb1-5ae987d0107a.png)
- Alta Perfil:
Si me encuentro en el popUp de Agregar y completo el campo "Nombre del Perfil" y le doy Enter, se realiza la consulta perfiles "Todos".
![image](https://user-images.githubusercontent.com/11543134/34257052-f8bd3842-e636-11e7-988c-b4d8fcd73c67.png)
- Si damos de alta un nuevo perfil y NO selecciono TODOS los menú, el perfil se agrega correctamente pero cuando vemos el detalle del mismo vemos que se inserta mal, SI se seleccionan TODOS los menú se guardan correctamente (Esta funcionalidad se replica en el EDITAR)
![image](https://user-images.githubusercontent.com/11543134/34257058-007904da-e637-11e7-86ae-158f02e4d461.png)
- Una vez que se dio de alta el usuario correctamente quitar los botones "Cancelar" y "Guardar" debe mostrar uno solo como "Cerrar"...
![image](https://user-images.githubusercontent.com/11543134/34257063-0b491c92-e637-11e7-89fb-0e4abdca84c7.png)
- Si editamos el campo "Nombre del Perfil" devuelve msj como que se edito correctamente pero no lo está realizando...
![image](https://user-images.githubusercontent.com/11543134/34257070-1206a4c8-e637-11e7-854e-6e42b3264de3.png)

**Comment by leoimoli** [comment]
- Permite editar perfiles iguales, mismo nombre y mismos permisos...
![image](https://user-images.githubusercontent.com/11543134/34299140-1a615bc6-e700-11e7-9247-7108fe3363ac.png)
Una vez que edito o agrego o realizó alguna operación las grillas deberían refrescar (actualizar) sin la necesidad de hacer click en el botón "Consultar" para que se actualicen los datos (ESTE PUNTO REPLICAR EN TODAS LAS PANTALLAS)
Alta Perfil:
Si me encuentro en el popUp de Agregar y completo el campo "Nombre del Perfil" y le doy Enter, se realiza la consulta perfiles "Todos".
![image](https://user-images.githubusercontent.com/11543134/34299144-235bcef0-e700-11e7-8e78-a71d40634a3b.png)
- Alta perfil: si completamos el campo nombre sin seleccionar ningún permiso devuelve bien el msj, pero si luego le damos cerrar y queremos agregar uno nuevo cuando seleccionamos un permiso devuelve msj de error...
![image](https://user-images.githubusercontent.com/11543134/34299151-2f5b5798-e700-11e7-92ed-d01946cfa759.png)

**Comment by alewalsh** [comment]
Ya se realizaron las correcciones mencionadas en este ticket, resta subir la aplicacion.

**Comment by alewalsh** [comment]
Aviso que se hicieron cambios en el Agregar Perfil que fueron pedidos informalmente por Lean.
- Al insertar un perfil, y luego querer volver a insertar otro donde se chequea uno de los grupos de checkbox, tira el mensaje del insertar anterior y oculta el botón de guardar.
**Solución**: Ahora limpia los campos después de guardar el perfil, para evitar que sostenga valores erróneos de los checkbox
- Luego de agregar un perfil, por defecto hace una consulta.
**Solución**: Ahora solo realiza la consulta en caso de estar visible la grilla, con el objetivo de actualizar los datos.

**Comment by leoimoli** [comment]
- Agregamos un perfil correctamente,
![image](https://user-images.githubusercontent.com/11543134/34561132-59aa86f0-f127-11e7-9862-40561bdf630e.png)
Luego queremos agregar uno nuevo, completamos el campo "Nombre" y seleccionamos un permiso no muestra el botón "Cerrar" y muestra el msj de que se guardo exitosamente el perfil.
![image](https://user-images.githubusercontent.com/11543134/34561140-614c04ce-f127-11e7-9000-057b7ba17da2.png)
Paginador
Si consultamos Perfiles por el filtro "Activo".
![image](https://user-images.githubusercontent.com/11543134/34561169-805e16ae-f127-11e7-9e2b-812c0663924b.png)
Luego seleccionamos "Inactivo", manteniendo la consulta por "Activo" y seleccionamos la pág. 2 consulta automáticamente por el filtro "Inactivo"...
![image](https://user-images.githubusercontent.com/11543134/34561171-8559dd14-f127-11e7-87ec-18324d97c0f9.png)
- Si me encuentro en la pág. 2 y activo o desactivo los perfiles de esa pág. al seleccionar el último devuelve un msj...
![image](https://user-images.githubusercontent.com/11543134/34561188-91caaf1a-f127-11e7-824b-64bd85f95368.png)
debería llevarte a la pág. 1

**Comment by alewalsh** [comment]
- El primer ítem fue corregido limpiando la creación al momento de mostrar el mensaje de éxito.
- Ya no realiza la consulta por el otro filtro si se cambia de pagina.
- Ya no muestra el mensaje si se terminan los items en la pagina donde se encuentra, si no que vuelve a la pagina anterior para seguir mostrando los items restantes.
