### ISSUE TITLE
Siniestros/Versión 1.0/Consultar Perfil(1) (#5)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#5]
El Radio Button "Buscar Por" por defecto debe estar seleccionado "Todos", hoy viene seleccionado "Por Filtros".

![image](https://cloud.githubusercontent.com/assets/11543134/24866875/e245bce2-1de1-11e7-983e-422eb56993c3.png)

**Comment by alewalsh** [comment]
Se arregló el radio por defecto y los filtros correspondientes para consultar perfiles.

**Comment by alewalsh** [comment]
Se comprobó que actualmente viene seleccionado por defecto el radio "Todos" y que deshabilita correctamente los campos.
