### ISSUE TITLE
Siniestros/ Versión 1.0/Consultar Perfil(2) (#6)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#6]
Al querer desactivar un perfil haciendo click en el botón "Desactivar" devuelve msj de error, "Error.
An error occurred while processing your request".

![image](https://cloud.githubusercontent.com/assets/11543134/24866939/13f012ce-1de2-11e7-87c3-e4cfdb07b392.png)

**Comment by alewalsh** [comment]
Localmente funciona, por lo que deberia probarse en el publicado antes de devolver a testing. Probablemente sea un problema del servicio publicado.

**Comment by alewalsh** [comment]
Se comprobó que al desactivar o activar un perfil, no tira errores y se mantiene en la pagina correspondiente.
