### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario(1) (#8)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#7]
Al querer agregar un usuario al darle al botón guardar devuelve msj de error, "Error.
An error occurred while processing your request".

![image](https://cloud.githubusercontent.com/assets/11543134/24868539/b72376f8-1de6-11e7-8156-2fc0665c3008.png)

**Comment by rominariquelme** [comment]
No sepudo reproducir el error

**Comment by alewalsh** [comment]
Los usuarios se agregan correctamente.
