### ISSUE TITLE
Siniestros/ Versión 1.0/ Munú Principal (#7)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#8]
En el menú principal cambiar de lugar "Consultar Usuarios" con "Agregar Usuarios".

![image](https://cloud.githubusercontent.com/assets/11543134/24868580/d919cb5e-1de6-11e7-8bfc-66c3bb021a05.png)

**Comment by alewalsh** [comment]
Se reorganizó el menú como fue pedido en la imagen.

**Comment by alewalsh** [comment]
Está correcto.
