### ISSUE TITLE
Siniestros/ Versión 1.0/ Agregar Usuario (2) (#9)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Legales-Proyecto-Registro-de-Siniestros#9]
El campo "Fecha de Alta" solo debe ser de fecha, hoy deja agregar caracteres de texto.

![image](https://cloud.githubusercontent.com/assets/11543134/24868616/f48166d6-1de6-11e7-96a9-fa5007cb2577.png)

**Comment by rominariquelme** [comment]
Se modifica el datepicker de todas las pantallas con fechas

**Comment by alewalsh** [comment]
Se probó y actualmente no deja escribir nada, solo es un selector de fecha.
